apps/common/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    'common.views',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', include('profiles.urls', 'profiles')),
    url(r'^contact/', 'contact', name='contact'),
    url(r'^about/', 'about', name='about'),
    url(r'^', include('rooms.urls', 'rooms')),
)

urlpatterns += patterns(
    'django.views.static',
    url(r'^static/(.*)$', 'serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(.*)$', 'serve', {'document_root': settings.MEDIA_ROOT}))

apps/profiles/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'profiles.views',
    url(r'^$', 'profile_detail', name='detail'),
)

apps/rooms/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'rooms.views',
    url(r'^(?P<shorten_id>\S{4,8})$', 'room_detail', name='detail'),
    url(r'^$', 'room_create', name='create')
)

apps/profiles/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=_('user'), related_name='profile')

    def __unicode__(self):
        return self.user.username


@receiver(models.signals.post_save, sender=get_user_model())
def create_profile(sender, created, instance, **kwargs):
    if created:
        Profile.objects.create(user=instance)

apps/rooms/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy


import short_url
from model_utils.models import TimeStampedModel


class Room(TimeStampedModel):

    people_in = models.PositiveSmallIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = _('Room')
        verbose_name_plural = _('Rooms')

    def __str__(self):
        return self.shorten_url

    def get_absolute_url(self):
        return reverse_lazy('rooms:detail', kwargs={'shorten_id': self.shorten_url})

    @property
    def shorten_url(self):
        return short_url.encode_url(self.id)

apps/stream/models.py
# prevent django.core.exceptions.ImproperlyConfigured: App with label stream is missing a models.py module.

apps/common/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class ContactForm(forms.Form):

    email = forms.EmailField(help_text=_('Your email'), required=False)
    body = forms.CharField(help_text=_('Something, that you want to tell us, it can be everything'),
                           widget=forms.Textarea())

apps/common/views.py
import logging

from django.views.generic import RedirectView, FormView, TemplateView
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.core.mail import EmailMessage


from skd_tools.mixins import ActiveTabMixin

from .forms import ContactForm

logger = logging.getLogger(__package__)


class MainView(RedirectView):
    url = reverse_lazy('rooms:create')


class ContactView(ActiveTabMixin, FormView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('rooms:create')
    active_tab = 'contact'

    def form_valid(self, form):
        from_email = settings.EMAIL_FROM_ADDRESS
        message = EmailMessage(subject='Feedback from {}'.format(form.cleaned_data['email']),
                               body=form.data['body'], to=[m for k, m in settings.ADMINS], from_email=from_email)
        message.content_subtype = 'html'
        try:
            message.send(fail_silently=True)
        except Exception:
            msg = 'Email server connection error'
            logger.exception(msg)

        messages.success(self.request, _('Thank you for your feedback, summoner! It\'s very important for ours team'))
        return super().form_valid(form)


class AboutView(ActiveTabMixin, TemplateView):
    template_name = 'about.html'
    active_tab = 'about'


main = MainView.as_view()
contact = ContactView.as_view()
about = AboutView.as_view()

apps/profiles/views.py
from django.views.generic import DetailView

from braces.views import LoginRequiredMixin

from .models import Profile


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile

    def get_object(self, queryset=None):
        return self.model.objects.get(user_id=self.request.user.id)


profile_detail = ProfileDetailView.as_view()

apps/rooms/views.py
from django.views.generic import CreateView, DetailView
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.http import Http404
from django.contrib import messages

from skd_tools.mixins import ActiveTabMixin
import short_url

from .models import Room


class RoomCreateView(ActiveTabMixin, CreateView):
    model = Room
    active_tab = 'home'
    template_name = 'landing.html'


class RoomDetailView(DetailView):
    model = Room

    def get_object(self):
        try:
            decoded_id = short_url.decode_url(self.kwargs.get('shorten_id'))
        except Exception:
            raise Http404()
        messages.success(self.request, 'Please share you microphone')
        return get_object_or_404(self.model, **{'id': decoded_id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        js_conf = {'addr': settings.SIGNALING_HOST}
        context['js_conf'] = js_conf
        return context


room_create = RoomCreateView.as_view()
room_detail = RoomDetailView.as_view()

apps/common/templates/about.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
    {% trans "Instamute.io: About" %}
{% endblock title %}
{% block extra_head %}
    <style type="text/css">
    h2.cover-heading {
        margin-top: 10%;
    }
    </style>
{% endblock extra_head %}
{% block content %}
<div class="inner cover">
    <h2 class="cover-heading">{% trans "Share your microphone" %}</h1>
        <img class="main_image" src="{% static "img/Firefox.png" %}" width='100%'>
        <img class="main_image" src="{% static "img/Chrome.png" %}" width='100%'>

    <h2 class="cover-heading">{% trans "That it!" %}</h1>
        <img class="main_image" src="{% static "img/Done.png" %}" width='100%'>
</div>
{% endblock content %}

apps/common/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <head>
    <title>{% trans "Instamute.io" %}</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <link href="{% static "css/cover.css" %}" rel="stylesheet">
    {% block extra_head %}
    {% endblock extra_head %}
    <style id="holderjs-style" type="text/css"></style>
  </head>
  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
      {% block carousel %}
      {% endblock carousel %}
        <div class="cover-container">
          <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="alert alert-success alert-dismissable" id="jsallert" style="display: none">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                </div>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              {{ message }}
            </div>
            {% endfor %}
            {% endif %}
              {% include "menu.html" %}
            </div>
          </nav>
          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </div>
    {% block js %}
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    {% endblock js %}
  </body>
</html>

apps/common/templates/contact.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap %}
{% block extra_head %}
    <style type="text/css">
        textarea { resize: none; }
        }
    </style>
{% endblock extra_head %}
{% block title %}
    {% trans "Instamute.io: Contact" %}
{% endblock title %}
{% block carousel %}
{% endblock carousel %}
{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form method="POST" action="{% url 'contact' %}">
        {% csrf_token %}
        <!--{{ form|bootstrap }}-->
            <div class="form-group">

                    <div class=" ">
                        <span class="input-group-addon">Email</span>
                        <input class=" form-control" id="id_email" name="email" type="email" placeholder="username@gmail.com">
                    </div>

            </div>




            <div class="form-group">


                    <div class=" ">
                        <span class="input-group-addon">Feedback</span>

                        <textarea class=" form-control" cols="40" id="id_body" name="body" rows="10" placeholder="Something, that you want to tell us, it can be everything"></textarea>




                    </div>

            </div>




            <button type="submit" name="submit" value="" class="btn btn-success btn-lg btn-block">
            {% trans "Send it!" %}
            </button>
        </form>
    </div>
</div>
{% endblock content %}

apps/common/templates/landing.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <head>
    <title>{% trans "Instamute.io" %}</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Dosis:300,400" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">

    <link href="{% static "css/landing.css" %}" rel="stylesheet">
</head>
  <body>
  <a id="how" href="{% url 'about' %}"><h3>?</h3></a>
 <div id="myCarousel" class="carousel slide" data-ride="carousel>
   <div class="carousel-inner">
     <div class="active item">
       <div class="fill" style="background-image:url('{% static "img/land.jpg" %}');">
         <div class="container" id="promo">
         <hr><hr>
            <h2>Let's play together</h2>
         <hr><hr>
             <form  id="centered" action="{% url 'rooms:create' %}" method="post">{% csrf_token %}
                 <button class="btn btn-primary btn-xlarge"><span class="glyphicon glyphicon-share-alt"></span>   Create Room</button>
             </form>
     </div>
     </div>

     <!--</div>-->
     <!--<div class="item">-->
       <!--<div class="fill" style="background-image:url('http://www.thelittlenerd.com/wp-content/uploads/2013/04/Acolyte-Lee-Sin-Wallpaper-League-of-Legends.jpg');">-->
         <!--<div class="container">-->

         <!--</div>-->
       <!--</div>-->
     <!--</div>-->
   <!--</div>-->
   <!--<div class="pull-center">-->
 	<!--<a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>-->
 	<!--<a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>-->
   <!--</div>-->
 </div>

  <script type='text/javascript'>

//  $(document).ready(function() {
//      $('.carousel').carousel();
//  });
  </script>
  </body>
</html>

apps/common/templates/menu.html
{% load i18n %}
<ul class="nav masthead-nav">
    <li {% if active_tab == 'home' %}
        class="active"{% endif %}>
        <a href="{% url "rooms:create" %}">
            {% trans "Home" %}
        </a>
    </li>
    <li {% if active_tab == 'about' %}
        class="active"{% endif %}>
        <a href="{% url 'about' %}">
            {% trans "How It Works" %}
        </a>
    </li>
    <li {% if active_tab == 'contact' %}
        class="active"{% endif %}>
        <a href="{% url 'contact' %}">
            {% trans "Feedback" %}
        </a>
    </li>
</ul>

apps/common/templates/pagination.html
{% load i18n %}
{% load spurl %}
{% if is_paginated %}
    <div class="paging-hold pagination clearfix">
        {% if page_obj.has_previous %}
            <div class="item prev"><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.previous_page_number }}" %}">{% trans "Prev" %}</a></div>
            <div class="item"><a href="{% spurl base=request.get_full_path set_query="page=1" %}">1</a></div>
        {% endif %}

        {% if page_obj.number > 3 %}<div class="item">...</div>{% endif %}

        {% if page_obj.has_previous and page_obj.previous_page_number != 1 %}
            <div class="item"><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.previous_page_number }}" %}">{{ page_obj.previous_page_number }}</a></div>
        {% endif %}

        <div class="item active"><a class="text-color {{ section.get_color_display }}" href="#">{{ page_obj.number }}</a></div>

        {% if page_obj.has_next and page_obj.next_page_number != page_obj.paginator.num_pages %}
            <div class="item"><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.next_page_number }}" %}">{{ page_obj.next_page_number }}</a></div>
        {% endif %}

        {% if page_obj.number != page_obj.paginator.num_pages and page_obj.paginator.num_pages != page_obj.next_page_number and page_obj.paginator.num_pages != page_obj.number|add:"2" %}<div class="item">...</div>{% endif %}

        {% if page_obj.has_next %}
            <div class="item"><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.paginator.num_pages }}" %}">{{ page_obj.paginator.num_pages }}</a></div>
            <div class="item next"><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.next_page_number }}" %}">{% trans "Next" %}</a></div>
        {% endif %}
    </div>
{% endif %}

{# FOR BOOTSTRAP #}
{% load spurl %}
{% if is_paginated %}
<div style="text-align: center;">
    <ul class="pagination pagination-lg">
        {% if page_obj.has_previous %}
            <li><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.previous_page_number }}" %}">«</a></li>
            <li><a href="{% spurl base=request.get_full_path set_query="page=1" %}">1</a></li>
        {% else %}
            <li class="disabled"><a href="#" onclick="return false;">«</a></li>
        {% endif %}

        {% if page_obj.number > 3 %}<li class="disabled"><a href="#" onclick="return false;">...</a></li>{% endif %}

        {% if page_obj.has_previous and page_obj.previous_page_number != 1 %}
            <li><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.previous_page_number }}" %}">{{ page_obj.previous_page_number }}</a></li>
        {% endif %}

        <li><a href="#">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next and page_obj.next_page_number != page_obj.paginator.num_pages %}
            <li><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.next_page_number }}" %}">{{ page_obj.next_page_number }}</a></li>
        {% endif %}

        {% if page_obj.number != page_obj.paginator.num_pages and page_obj.paginator.num_pages != page_obj.next_page_number and page_obj.paginator.num_pages != page_obj.number|add:"2" %}<li class="disabled"><a href="#" onclick="return false;">...</a></li>{% endif %}

        {% if page_obj.has_next %}
            <li><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.paginator.num_pages }}" %}">{{ page_obj.paginator.num_pages }}</a></li>
            <li><a href="{% spurl base=request.get_full_path set_query="page={{ page_obj.next_page_number }}" %}">»</a></li>
        {% else %}
            <li class="disabled"><a href="#" onclick="return false;">»</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}

apps/common/templates/profiles/profile_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Profile detail" %} | {{ block.super }}{% endblock title %}

{% block content %}
    <h1>Hello, {{ request.user.username }}</h1>
{% endblock content%}

apps/common/templates/rooms/modals.html
{% load i18n %}
<!-- /.modal-start -->
<div class="modal fade" id="max_size_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{% trans "Hello, summoner, we have problem there" %}</h4>
      </div>
      <div class="modal-body">
        <p>{% trans "The limit of members for this room was exceeded, and we can not connect you with your buddies (Sorry for that)." %}
        {% trans "You can easily" %} <a href="{% url 'rooms:create' %}">{% trans "create a new one" %}</a>
        {% trans "or you can wait till somebody will leave this room and try to connect one more time, good luck!" %}
        </p>
      </div>
      <div class="modal-footer">
        <a href="{% url 'rooms:create' %}"><button type="button" class="btn btn-primary">{% trans "Create a new room without anybody" %}</button></a>
        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="modal-failure">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{% trans "Hello, summoner, we have problem there" %}</h4>
      </div>
      <div class="modal-body">
        <p>{% trans "We failure to connect you with some your buddies (Sorry for that)." %}
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">{% trans "Back to talk" %}</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="failed_media_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{% trans "Hello, summoner, we have problem there" %}</h4>
      </div>
      <div class="modal-body">
        <p>{% trans "We failure get access to your microphone. Please reload the page and make sure that this action is allowed" %}
        </p>
      </div>
    </div>
  </div>
</div>

apps/common/templates/rooms/room_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block extra_head %}
<link rel="stylesheet" href="{% static "css/slider.css" %}">
<link rel="stylesheet" href="{% static "css/room_detail.css" %}">
{% endblock extra_head %}
{% block title %}
{% trans "Instamute.io: " %} {{ object.shorten_url }}
{% endblock title %}
{% block content %}
<div class="row headroom">
  <h4>{% trans "Copy this link to share this room with your mates" %}</h4>
  <div class="col-md-6 col-md-offset-3">
    <div class="input-group">
      <input name="copy_link" id="copy_link" type="text" disabled value="{{ request.build_absolute_uri }}" class="form-control" >
      <span class="input-group-btn">
        <button type="button" class="btn btn-default btn-lg popover-dismiss"
                type="button" id="copy_link_button" data_link="{% static "js/ZeroClipboard.swf" %}">
          <span class="glyphicon glyphicon-link"></span>
        </button>
      </span>
    </div>
  </div>
  <div class="col-md-3">
    <div class="row">
      <div class="col-md-3 col-md-offset-4">
{#        <a href="#">#}
{#        <button type="button" class="btn btn-default btn-sm">#}
{#        <span class="glyphicon glyphicon-plus"></span>#}
{#        </button>#}
{#        </a>#}
      </div>
      <div class="col-md-2 col-md-offset-1">
{#        <a href="">#}
{#        <button type="button" class="btn btn-default btn-sm">#}
{#        <span class="glyphicon glyphicon-trash">#}
{#        </span>#}
{#        </button>#}
{#        </a>#}
      </div>
    </div>
  </div>
</div>
<div class="row" style="margin-top:5%;">
  <div class="col-md-6">
      <button id="mute_me" class="btn btn-lg"><span class="glyphicon-microphone"></span>      Mute me</button>
    </div>

    <div class="col-md-6">
      <button id="mute_all" class="btn btn-lg" onclick="mute_controller(this);"><span class="glyphicon-microphone"></span>      Instamute</button>
    </div>
</div>

<div class="row" id="videos">
  <div class="row stream" id="my_stream">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-1">
          <button type="button" class="btn btn btn-lg"><span class="glyphicon glyphicon-user"></span>
              <i id="username">Me</i></button>
        </div>
        <audio id="local-audio" hidden muted></audio>
        <div class="col-md-4 col-md-offset-3">
          <input id="volume_range" type="range" step="0.01" min="0" max="1" value="1"/>
        </div>
        <div class="col-md-1 col-md-offset-2">
          <button type="button" class="btn btn btn-lg" id='gaymute' onclick="togglePlayPause(this)">
            <span class="glyphicon glyphicon-headphones"></span>
             Mute
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
{% include "rooms/modals.html" %}
<div class="row">
    <div id="disqus_thread"></div>
</div>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock content %}
{% block js %}
{{ block.super }}
<script>
    var SiganlingAddr = "{{js_conf.addr}}";
</script>
<script type="text/javascript" src="{% static "js/microevent.js" %}" ></script>
<script type="text/javascript" src="{% static "js/hark.js" %}" ></script>
<script type="text/javascript" src="{% static "js/voice_app.js" %}" ></script>
<script type="text/javascript" src="{% static "js/app.js" %}" ></script>
<script type="text/javascript" src="{% static "js/bootstrap-slider.js" %} "></script>
<script type="text/javascript" src="{% static "js/jquery.zclip.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/room_detail.js" %} "></script>
{% endblock js %}

apps/common/templates/rooms/room_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
{% trans "Room create" %}
{% endblock title %}
{% block extra_head %}
    <style type="text/css">
    .carousel{
        background-repeat: no-repeat;
        min-height: 585px;
        text-shadow: 1px 1px 5px black, 0 0 2em #26292e;
    }
    .main_image{
        box-shadow: 0 0 20px rgba(0,0,0,0.5);
    }
    .carousel-caption{
        bottom: 200px !important; 
        text-shadow: 1px 1px 5px black, 0 0 2em #26292e;
    }
    .carousel-caption .btn-lg{
        margin-top: 2%;
        text-shadow: 1px 1px 5px black, 0 0 2em #26292e;
    }
    .site-wrapper{
        display: block;
    }
    .site-wrapper-inner{
        display: block;
    }
    .row.main{
        text-shadow: 1px 1px 5px black, 0 0 2em #26292e;
    }
    .twitter{
        background-image: url({% static "img/TR_Icon.png" %});
        background-repeat: no-repeat;
        background-size: 30%;
        min-height: 100px;
        background-position: center;
    }
    .lolking{
        background-image: url({% static "img/lolking.png" %});
        background-repeat: no-repeat;
        background-size: 30%;
        min-height: 100px;
        background-position: center;
    }
    .github{
        background-image: url({% static "img/Github.png" %});
        background-repeat: no-repeat;
        background-size: 15%;
        min-height: 100px;
        background-position: center;
        }
    </style>
{% endblock extra_head %}
{% block carousel %}
    <div class="carousel">
        <div class="item active">
        <img class="main_image" src="{% static "img/teambuilder-wallpaper.png" %}" width='100%'>
          <div class="container">
            <div class="carousel-caption">
                <div class="cover">
                    <h1><strong> {% trans "Truly simple voice room" %}</strong>
                    </h1>
                    <form action="{% url 'rooms:create' %}" method="post">{% csrf_token %}
                        <p class="lead">
                        <button class="btn btn-lg btn-success" name="submit" type="submit">{% trans "Create Room" %}</button>
                        </p>
                    </form>
                </div>
            </div>
          </div>
        </div>
    </div>

<div class="row main">
    <div class="col-sm-4">
    	<div class="services-box-1-icon">
    		<i class="fa fa-laptop"></i>
    	</div>
        <h3>No Payment</h3>
        <p>
          No registration, no activation keys anymore
        </p>
        <div class="services-box-1-button">
        </div>
    </div>
    <div class="col-sm-4">
    	<div class="services-box-1-icon">
    		<i class="fa fa-desktop"></i>
    	</div>
        <h3>Easy to use</h3>
        <p>
           Just press fucking button and allow your microphone. Otherwise ranked games are not yours.
        </p>
        <div class="services-box-1-button">
        </div>
    </div>
    <div class="col-sm-4">
    	<div class="services-box-1-icon">
    		<i class="fa fa-tablet"></i>
    	</div>
        <h3>No retards</h3>
        <p>
            Helps dogging teammates with intellectual or cognitive disability
        </p>
        <div class="services-box-1-button">
        </div>
    </div>
</div>

{% endblock carousel %}
{% block content %}
<div class="container-main">
    
</div>
{% endblock content %}

apps/common/templates/rooms/text_chat.html
<div class="row" style="margin-top:5%;">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-body" id="chatters">
                <ul id="chat-stub" hidden class="chat">
                    <li class="right clearfix">
                        <span class="chat-img pull-right">
                            <img src="http://placehold.it/40/FA6F57/fff&amp;text=Hello" alt="User Avatar" class="img-circle">
                         </span>
                        <div class="chat-body clearfix">
                            <div class="header">
                            </div>
                            <p id="u-message">
                            </p>
                        </div>
                    </li>
                    </ul>
            </div>
            <div class="panel-footer">
                <div class="input-group">
                    <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here...">
                    <span class="input-group-btn">
                        <button class="btn btn-warning btn-sm" id="btn-chat">
                            Send</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>